[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = "0.5.1"

[dependencies]
dotenv = "0.15.0"
rand = "0.8.5"
rsmod-pathfinder = "5.0.4"
cache = { path = "../cache" }
io = { path = "../io" }
math = { path = "../math" }
packet = { path = "../packet" }

[[bench]]
name = "fib"
harness = false